apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.prefix }}-hatunnel-data-pv"
  namespace: "{{ .Values.namespace }}"
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  hostPath:
    path: " {{ .Values.local-path }}"
    type: DirectoryOrCreate
  claimRef:
    namespace: "{{ .Values.namespace }}"
    name: "{{ .Values.prefix }}-hatunnel-data-pvc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.prefix }}-hatunnel-data-pvc"
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-hostpath
